server.port: 0
spring:
  application:
    name: bar-processor
  cloud:
    function:
      definition: processFoo
    stream:
      defaultBinder: rabbit
      bindings:
        processFoo-in-0:
          destination: foo-source
          group: foo-source-group
          consumer:
            maxAttempts: 4
            backOffInitialInterval: 15000
            backOffMaxInterval: 60000
        processFoo-out-0:
          destination: foo-result
